Parameters:
  cluster:
    Type: String
  DesiredCount:
    Type: String
  Image:
    Type: String
  Role:
    Type: String
  TargetGroupArn:
    Type: String

Resources:
  service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      Role: !Ref Role
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: liteticket
          ContainerPort: 8817
          TargetGroupArn: !Ref TargetGroupArn
TaskDefinition:
  Type: AWS::ECS::TaskDefinition
  Properties:
    Family: Service
    ContainerDefinitions:
      - Name: liteticket
        Image: !Ref Image
        Memory: 512
        PortMapping:
          - ContainerPort: 80
